const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const OWNER='varezproduccionindependiente-collab', REPO='varez-multimedios-app', WORKFLOW='render-multimedios.yml';
const S={file:null,dur:0,mode:'auto',category:'Entrevista',settings:{captions:true,qa:true,reframe:true},ff:null,mounted:false,jobId:null,release:null,clips:[]};
const LS={pin:'varez_multimedios_pin',gemini:'varez_gemini_key',groq:'varez_groq_key',github:'varez_github_pat',release:'varez_worker_release'};
function esc(s=''){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function fmt(sec){sec=Math.max(0,Number(sec)||0);return Math.floor(sec/60)+':'+String(Math.floor(sec%60)).padStart(2,'0')}
function progress(p,l,d=''){p=Math.max(0,Math.min(100,Math.round(p)));$('#progress').style.display='block';$('#ppct').textContent=p+'%';$('#pbar').style.width=p+'%';$('#plabel').textContent=l;$('#log').textContent=d;$('#log').className='log'}
function fail(msg){$('#log').textContent=msg;$('#log').className='log error';throw new Error(msg)}
function cfg(){return{gemini:localStorage.getItem(LS.gemini)||'',groq:localStorage.getItem(LS.groq)||'',github:localStorage.getItem(LS.github)||''}}
function ensureLogin(){if(localStorage.getItem(LS.pin)!=='053362')$('#loginModal').classList.add('show')}
function ensureConfig(){const c=cfg();if(!c.gemini||!c.groq||!c.github){openSettings();return false}return true}
function openSettings(){const c=cfg();$('#geminiKey').value=c.gemini;$('#groqKey').value=c.groq;$('#githubToken').value=c.github;$('#settingsModal').classList.add('show')}
$('#settingsBtn').onclick=openSettings;$('#cancelSettings').onclick=()=>$('#settingsModal').classList.remove('show');
$('#saveSettings').onclick=()=>{const g=$('#geminiKey').value.trim(),q=$('#groqKey').value.trim(),h=$('#githubToken').value.trim();if(!g||!q||!h){$('#settingsMsg').textContent='Completá las tres claves.';$('#settingsMsg').className='help error';return}localStorage.setItem(LS.gemini,g);localStorage.setItem(LS.groq,q);localStorage.setItem(LS.github,h);$('#settingsMsg').textContent='Guardado en este iPhone.';$('#settingsMsg').className='help ok';setTimeout(()=>$('#settingsModal').classList.remove('show'),450)};
$('#login').onclick=()=>{const v=$('#pin').value.trim();if(v!=='053362'){localStorage.removeItem(LS.pin);$('#loginErr').textContent='Clave incorrecta.';return}localStorage.setItem(LS.pin,v);$('#loginModal').classList.remove('show');if(!ensureConfig())openSettings()};

$('#choose').onclick=e=>{e.preventDefault();$('#file').click()};$('#file').onchange=()=>pick($('#file').files[0]);
const drop=$('#drop');['dragenter','dragover'].forEach(x=>drop.addEventListener(x,e=>{e.preventDefault()}));drop.addEventListener('drop',e=>{e.preventDefault();pick(e.dataTransfer.files[0])});
function pick(f){if(!f)return;if(f.size>2147483648)return alert('Por ahora el video para Gemini debe pesar menos de 2 GB.');S.file=f;S.ff=null;S.mounted=false;const v=$('#preview');if(v.src)URL.revokeObjectURL(v.src);v.src=URL.createObjectURL(f);v.onloadedmetadata=()=>{S.dur=v.duration||0;if(S.dur>1800)alert('La beta admite notas de hasta 30 minutos.');$('#meta').style.display='block';$('#meta').innerHTML='<b>'+esc(f.name)+'</b><span>'+(f.size/1024/1024).toFixed(1)+' MB · '+fmt(S.dur)+'</span>'}}
$$('[data-mode]').forEach(b=>b.onclick=()=>{$$('[data-mode]').forEach(x=>x.classList.remove('active'));b.classList.add('active');S.mode=b.dataset.mode;$('#request').style.display=S.mode==='specific'?'block':'none'});
$$('.chip').forEach(b=>b.onclick=()=>{$$('.chip').forEach(x=>x.classList.remove('active'));b.classList.add('active');S.category=b.textContent.trim()});
$$('[data-setting]').forEach(t=>t.onclick=()=>{t.classList.toggle('on');S.settings[t.dataset.setting]=t.classList.contains('on')});

async function gh(url,opt={}){const t=cfg().github;const headers={Accept:'application/vnd.github+json','X-GitHub-Api-Version':'2026-03-10',Authorization:'Bearer '+t,...(opt.headers||{})};const r=await fetch(url,{...opt,headers});if(!r.ok){const x=await r.text();throw new Error('GitHub: '+r.status+' '+x.slice(0,350))}if(r.status===204)return null;return r.json()}
async function ensureRelease(){if(S.release)return S.release;progress(4,'Preparando editor remoto…','Conectando con GitHub.');const list=await gh(`https://api.github.com/repos/${OWNER}/${REPO}/releases?per_page=100`);let rel=list.find(x=>x.tag_name==='varez-worker-storage');if(!rel){rel=await gh(`https://api.github.com/repos/${OWNER}/${REPO}/releases`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({tag_name:'varez-worker-storage',target_commitish:'main',name:'Varez Worker Storage',body:'Almacenamiento temporal privado para Varez Multimedios.',draft:true,prerelease:false})})}S.release=rel;localStorage.setItem(LS.release,String(rel.id));return rel}
async function listAssets(){const rel=await ensureRelease();return gh(`https://api.github.com/repos/${OWNER}/${REPO}/releases/${rel.id}/assets?per_page=100`)}
async function deleteAsset(asset){await gh(`https://api.github.com/repos/${OWNER}/${REPO}/releases/assets/${asset.id}`,{method:'DELETE'})}
async function uploadAsset(name,blob,type='application/octet-stream'){const rel=await ensureRelease();const existing=(await listAssets()).filter(x=>x.name===name);for(const x of existing)await deleteAsset(x);const url=`https://uploads.github.com/repos/${OWNER}/${REPO}/releases/${rel.id}/assets?name=${encodeURIComponent(name)}`;const r=await fetch(url,{method:'POST',headers:{Authorization:'Bearer '+cfg().github,Accept:'application/vnd.github+json','X-GitHub-Api-Version':'2026-03-10','Content-Type':type},body:blob});if(!r.ok)throw new Error('No pude subir '+name+' a GitHub: '+r.status+' '+(await r.text()).slice(0,300));return r.json()}
async function dispatch(){const rel=await ensureRelease();await gh(`https://api.github.com/repos/${OWNER}/${REPO}/actions/workflows/${WORKFLOW}/dispatches`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({ref:'main',inputs:{release_id:String(rel.id),job_id:S.jobId}})})}

async function geminiUpload(file){const key=cfg().gemini,mime=file.type||'video/mp4';progress(8,'Subiendo video a Gemini…','El video se usa solo para elegir los cinco mejores momentos.');const start=await fetch('https://generativelanguage.googleapis.com/upload/v1beta/files',{method:'POST',headers:{'x-goog-api-key':key,'X-Goog-Upload-Protocol':'resumable','X-Goog-Upload-Command':'start','X-Goog-Upload-Header-Content-Length':String(file.size),'X-Goog-Upload-Header-Content-Type':mime,'Content-Type':'application/json'},body:JSON.stringify({file:{display_name:file.name}})});if(!start.ok)throw new Error('Gemini upload: '+start.status+' '+(await start.text()).slice(0,300));const uploadUrl=start.headers.get('x-goog-upload-url');if(!uploadUrl)throw new Error('Gemini no devolvió la URL de carga.');const up=await fetch(uploadUrl,{method:'POST',headers:{'X-Goog-Upload-Offset':'0','X-Goog-Upload-Command':'upload, finalize','Content-Type':mime},body:file});if(!up.ok)throw new Error('Gemini upload: '+up.status+' '+(await up.text()).slice(0,300));let info=await up.json();for(let i=0;i<120&&info.file?.state==='PROCESSING';i++){progress(12,'Gemini está procesando el video…','Puede tardar unos minutos según el tamaño.');await new Promise(r=>setTimeout(r,3000));const g=await fetch('https://generativelanguage.googleapis.com/v1beta/'+info.file.name,{headers:{'x-goog-api-key':key}});if(!g.ok)throw new Error('Gemini file status: '+g.status);info={file:await g.json()}}if(info.file?.state&&info.file.state!=='ACTIVE')throw new Error('Gemini no pudo preparar el video. Estado: '+info.file.state);return info.file}
async function geminiSelect(fileInfo){progress(20,'Gemini está mirando la nota completa…','Buscando momentos que realmente funcionen como reels.');const pol=S.category.toLowerCase().includes('pol')?'Para contenido político, seleccioná por claridad, relevancia periodística, autosuficiencia y valor informativo. No favorezcas ni perjudiques partidos, candidatos o funcionarios; no hagas rankings ni recomendaciones electorales.':'';const prompt=`Sos editor senior de clips para Varez Servicios para Multimedios. Mirá y escuchá el video completo. Elegí EXACTAMENTE 5 fragmentos distintos que funcionen como reels por sí solos. Cada uno debe durar entre 25 y 58 segundos. Priorizá respuestas completas, frases memorables, datos concretos, consecuencias, explicaciones claras, emoción, sorpresa o humor según el contenido. Evitá saludos, introducciones, relleno, respuestas que dependan de contexto externo y cortes a mitad de idea. Si una pregunta breve inmediatamente anterior mejora la respuesta, incluí la pregunta y devolvé el segundo exacto en que termina como question_end; si no, usá -1. No superpongas los cinco clips. Categoría: ${S.category}. Modo: ${S.mode}. Pedido específico: ${$('#request').value.trim()||'ninguno'}. ${pol} Devolvé segundos absolutos desde el inicio del video.`;const body={contents:[{parts:[{text:prompt},{file_data:{mime_type:fileInfo.mimeType||S.file.type||'video/mp4',file_uri:fileInfo.uri}}]}],generationConfig:{responseMimeType:'application/json',responseSchema:{type:'OBJECT',properties:{clips:{type:'ARRAY',minItems:5,maxItems:5,items:{type:'OBJECT',properties:{title:{type:'STRING'},start:{type:'NUMBER'},end:{type:'NUMBER'},question_end:{type:'NUMBER'},reason:{type:'STRING'}},required:['title','start','end','question_end','reason']}}},required:['clips']}}};const r=await fetch('https://generativelanguage.googleapis.com/v1beta/models/gemini-3.8-flash:generateContent',{method:'POST',headers:{'x-goog-api-key':cfg().gemini,'Content-Type':'application/json'},body:JSON.stringify(body)});if(!r.ok)throw new Error('Gemini análisis: '+r.status+' '+(await r.text()).slice(0,500));const d=await r.json(),txt=(d.candidates?.[0]?.content?.parts||[]).map(x=>x.text||'').join('');let out;try{out=JSON.parse(txt)}catch{throw new Error('Gemini no devolvió un JSON válido.')}if(!Array.isArray(out.clips)||out.clips.length!==5)throw new Error('Gemini no devolvió exactamente 5 clips.');return out.clips.map((c,i)=>({title:String(c.title||'Clip '+(i+1)),start:Math.max(0,Number(c.start)||0),end:Math.min(S.dur,Number(c.end)||0),question_end:Number(c.question_end??-1),reason:String(c.reason||'')})).filter(c=>c.end>c.start+15)}
async function geminiDelete(fileInfo){try{await fetch('https://generativelanguage.googleapis.com/v1beta/'+fileInfo.name,{method:'DELETE',headers:{'x-goog-api-key':cfg().gemini}})}catch{}}

class MiniFFmpeg{constructor(){this.worker=null;this.pending=new Map();this.loaded=false}async load(){if(this.loaded)return;const base='https://cdn.jsdelivr.net/npm/@ffmpeg/core@0.12.10/dist/umd';const [j,w]=await Promise.all([fetch(base+'/ffmpeg-core.js'),fetch(base+'/ffmpeg-core.wasm')]);const coreURL=URL.createObjectURL(await j.blob()),wasmURL=URL.createObjectURL(await w.blob());const ws=`let ffmpeg=null;async function loadCore(d){importScripts(d.coreURL);ffmpeg=await self.createFFmpegCore({mainScriptUrlOrBlob:d.coreURL+'#'+btoa(JSON.stringify({wasmURL:d.wasmURL}))});return true}function exec(d){ffmpeg.setTimeout(d.timeout??-1);ffmpeg.exec('-nostdin','-y',...d.args);const r=ffmpeg.ret;ffmpeg.reset();return r}self.onmessage=async e=>{const{id,type,data}=e.data;try{let o;if(type==='load')o=await loadCore(data);else if(type==='exec')o=exec(data);else if(type==='mkdir'){ffmpeg.FS.mkdir(data.path);o=true}else if(type==='mount'){ffmpeg.FS.mount(ffmpeg.FS.filesystems[data.fsType],data.options,data.mountPoint);o=true}else if(type==='read'){o=ffmpeg.FS.readFile(data.path);self.postMessage({id,ok:true,data:o},[o.buffer]);return}else if(type==='delete'){try{ffmpeg.FS.unlink(data.path)}catch{}o=true}else throw Error('ffmpeg');self.postMessage({id,ok:true,data:o})}catch(x){self.postMessage({id,ok:false,error:String(x.message||x)})}}`;const u=URL.createObjectURL(new Blob([ws],{type:'text/javascript'}));this.worker=new Worker(u);this.worker.onmessage=e=>{const m=e.data,p=this.pending.get(m.id);if(!p)return;this.pending.delete(m.id);m.ok?p.resolve(m.data):p.reject(Error(m.error))};await this.send('load',{coreURL,wasmURL});this.loaded=true}send(type,data,transfer=[]){const id=crypto.randomUUID();return new Promise((resolve,reject)=>{this.pending.set(id,{resolve,reject});this.worker.postMessage({id,type,data},transfer)})}exec(args,t=-1){return this.send('exec',{args,timeout:t})}mkdir(path){return this.send('mkdir',{path})}mount(fsType,options,mountPoint){return this.send('mount',{fsType,options,mountPoint})}read(path){return this.send('read',{path})}del(path){return this.send('delete',{path})}terminate(){try{this.worker?.terminate()}catch{}this.worker=null;this.loaded=false}}
async function getFF(){if(!S.ff)S.ff=new MiniFFmpeg();await S.ff.load();if(!S.mounted){try{await S.ff.mkdir('/input')}catch{}await S.ff.mount('WORKERFS',{files:[S.file]},'/input');S.mounted=true}return S.ff}
function ext(){const x=S.file.name.toLowerCase();return x.endsWith('.mov')?'.mov':'.mp4'}
async function groqWords(audioBytes,index){progress(36+index*7,'Subtitulando clip '+(index+1)+'/5…','Whisper Large V3 está escuchando este fragmento.');const fd=new FormData();fd.append('file',new File([audioBytes],'clip.mp3',{type:'audio/mpeg'}));fd.append('model','whisper-large-v3');fd.append('language','es');fd.append('response_format','verbose_json');fd.append('timestamp_granularities[]','word');const r=await fetch('https://api.groq.com/openai/v1/audio/transcriptions',{method:'POST',headers:{Authorization:'Bearer '+cfg().groq},body:fd});if(!r.ok)throw new Error('Groq: '+r.status+' '+(await r.text()).slice(0,500));const d=await r.json();return (d.words||[]).map(w=>({word:String(w.word||'').trim(),start:Number(w.start)||0,end:Number(w.end)||0})).filter(w=>w.word)}
async function prepareOne(c,i){const ff=await getFF(),dur=c.end-c.start,srcStart=Math.max(0,c.start-4),srcEnd=Math.min(S.dur,c.end+4),srcDur=srcEnd-srcStart;const audio=`/a${i}.mp3`,source=`/s${i}.mp4`;let r=await ff.exec(['-ss',String(c.start),'-t',String(dur),'-i','/input/'+S.file.name,'-vn','-ac','1','-ar','16000','-c:a','libmp3lame','-b:a','64k',audio],10*60*1000);if(r!==0)throw new Error('No pude extraer el audio del clip '+(i+1));const ab=await ff.read(audio);await ff.del(audio);const words=await groqWords(ab,i);progress(40+i*7,'Preparando fuente '+(i+1)+'/5…','Corte rápido del video original.');r=await ff.exec(['-ss',String(srcStart),'-t',String(srcDur),'-i','/input/'+S.file.name,'-map','0:v:0','-map','0:a?','-c','copy','-movflags','+faststart',source],10*60*1000);if(r!==0){r=await ff.exec(['-ss',String(srcStart),'-t',String(srcDur),'-i','/input/'+S.file.name,'-vf','scale=1920:1920:force_original_aspect_ratio=decrease','-c:v','libx264','-preset','ultrafast','-crf','20','-c:a','aac','-b:a','160k','-movflags','+faststart',source],20*60*1000);if(r!==0)throw new Error('No pude preparar el video del clip '+(i+1))}const vb=await ff.read(source);await ff.del(source);const name=`${S.jobId}-source-${String(i+1).padStart(2,'0')}.mp4`;progress(44+i*7,'Subiendo fragmento '+(i+1)+'/5…','Se guarda temporalmente en un release privado de GitHub.');await uploadAsset(name,new Blob([vb],{type:'video/mp4'}),'video/mp4');return{...c,source_offset:c.start-srcStart,question_end_rel:c.question_end>=c.start&&c.question_end<c.end?c.question_end-c.start:0,words,captions:S.settings.captions,qa:S.settings.qa,reframe:S.settings.reframe}}
async function stageAll(clips){const out=[];for(let i=0;i<5;i++)out.push(await prepareOne(clips[i],i));return out}
async function uploadManifest(clips){const manifest={version:1,job_id:S.jobId,created_at:new Date().toISOString(),category:S.category,clips};await uploadAsset(`${S.jobId}-manifest.json`,new Blob([JSON.stringify(manifest)],{type:'application/json'}),'application/json')}
async function poll(){const started=Date.now();while(Date.now()-started<45*60*1000){const a=await listAssets(),outs=a.filter(x=>x.name.startsWith(S.jobId+'-output-')&&x.name.endsWith('.mp4')).sort((x,y)=>x.name.localeCompare(y.name));progress(86+outs.length*2.5,'Editando en GitHub…',outs.length+'/5 clips terminados. Podés dejar esta pantalla abierta.');if(outs.length>=5){await showOutputs(outs.slice(0,5));progress(100,'Listo','Los cinco videos están terminados.');return}await new Promise(r=>setTimeout(r,8000))}throw new Error('El render tardó demasiado. Revisá GitHub Actions.')}
async function assetBlob(asset){const r=await fetch(asset.url,{headers:{Authorization:'Bearer '+cfg().github,Accept:'application/octet-stream','X-GitHub-Api-Version':'2026-03-10'}});if(!r.ok)throw new Error('No pude descargar '+asset.name);return r.blob()}
async function showOutputs(assets){const g=$('#grid');g.innerHTML='';for(let i=0;i<assets.length;i++){const blob=await assetBlob(assets[i]),url=URL.createObjectURL(blob),c=S.clips[i]||{};const el=document.createElement('article');el.className='clip';el.innerHTML=`<h4>${esc(c.title||'Clip '+(i+1))}</h4><p>${esc(c.reason||'')}</p>`;const v=document.createElement('video');v.controls=true;v.playsInline=true;v.src=url;el.appendChild(v);const a=document.createElement('a');a.className='download';a.href=url;a.download=`Varez_${String(i+1).padStart(2,'0')}_${(c.title||'clip').replace(/[^a-z0-9áéíóúñ_-]+/gi,'_')}.mp4`;a.textContent='Descargar MP4';el.appendChild(a);g.appendChild(el)}$('#results').style.display='block';$('#results').scrollIntoView({behavior:'smooth',block:'start'})}

$('#go').onclick=async()=>{if(!S.file)return alert('Primero elegí un video.');if(S.dur>1800)return alert('Máximo 30 minutos en esta beta.');if(!ensureConfig())return;$('#go').disabled=true;$('#results').style.display='none';S.jobId=crypto.randomUUID().replaceAll('-','').slice(0,16);try{await ensureRelease();const gf=await geminiUpload(S.file);let clips;try{clips=await geminiSelect(gf)}finally{geminiDelete(gf)}if(clips.length!==5)fail('No pude obtener cinco clips válidos.');S.clips=clips;progress(32,'Tengo los 5 momentos','Ahora preparo subtítulos y los fragmentos fuente.');const staged=await stageAll(clips);if(S.ff){S.ff.terminate();S.ff=null;S.mounted=false}await uploadManifest(staged);progress(82,'Mandando a edición remota…','GitHub FFmpeg va a producir los cinco MP4.');await dispatch();await poll()}catch(e){progress(100,'Hubo un problema',e.message||String(e));$('#log').className='log error';alert(e.message||e)}finally{$('#go').disabled=false}};
ensureLogin();if(localStorage.getItem(LS.pin)==='053362'&&!ensureConfig())openSettings();